### ISSUE TITLE
PHP7 incompatibility

### ISSUE THREAD

**Issue by koloszko** [glavweb/GlavwebUploaderDropzoneBundle#1]
In DropzoneType.php line 89 should be
$files = $entity->{$dataPropertyAnnotation['nameGetFunction']}();
to be compatible with php7

**Comment by nilov** [comment]
Thank you for your answer! I am not test bundle on PHP7. Create pull request, please.

**Comment by nilov** [comment]
Merged in https://github.com/glavweb/GlavwebUploaderDropzoneBundle/commit/18904e0a13a2f2e2860488509d8ebdb52ce4995a
